config/routes.rb
Rails.application.routes.draw do
  resources :questions

  root 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  validates :title, presence: true, length: { minimum: 3 }
  validates :body, presence: true, length: { minimum: 3 }

  def time
    created_at.strftime('%Y-%m-%d %H:%M:%S')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index; end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def show
    @question = Question.find_by id: params[:id]
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy!
    redirect_to questions_path
  end

  def edit
    @question = Question.find_by id: params[:id]
  end

  def update
    @question = Question.find_by id: params[:id]
    if @question.update(question_params)
      redirect_to questions_path
    else
      render :edit
    end
  end

  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new question_params
    if @question.save
      redirect_to questions_path
    else
      render :new
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :body, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AskApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag '/assets/application.js', 'data-turbolinks-track': 'reload' %>
    <%= turbo_frame_tag 'turbo-frame' %>
    <%= javascript_tag %>
    <%= javascript_importmap_tags %>

  </head>
 <header class="p-3 bg-dark">
    <div class="container-fluid"> 
      <nav class="d-flex flex-wrap align-items-center justify-content-center justify-content-center">
          <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            <li><%= link_to "Home", root_url, class: 'nav-link px-2 text-white' %></li>
            <li><%= link_to "Questions list", questions_url, class: 'nav-link px-2 text-white'%></li>
          </ul>
      </nav>
    </div>
  </header>

  <main class="container mt-3">
    <% flash.each do |k, v|%>
      <%k.to_s + " " + v.to_s %>
    <% end %>

    <%= yield %>
  </main>
</html>

app/views/pages/index.html.erb
<div class="text-center">
  <h1>Hello world</h1>

  <div>
    <p>
    This is my first Rails application where you can ask questions and provide answers.
    </p>
  </div>
  <div><%= Time.now%></div>   
</div>

app/views/questions/_form.html.erb
<%= render 'shared/form_errors', object: @question %>

<%= form_with(model: @question, url: questions_path) do |f| %>
<div class="field<%= ' field_error' if @question.errors.any? %>">
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :title %>
    </div>

    <div class="col-sm-10">
      <%= f.text_field :title, placeholder: 'Title', class: 'form-control' %>
    </div>
  </div>

  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :body %>
    </div>

    <div class="col-sm-10">
      <%= f.text_area :body, class: 'form-control' %>
    </div>
  </div>

  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :description %>
    </div>

    <div class="col-sm-10">
      <%= f.text_area :description %>
    </div>
  </div>
</div>
  <%= f.submit "Submit question!", class: 'btn btn-primary' %>
<% end %>

app/views/questions/edit.html.erb
<h1>Edit question</h1>

<%= form_for @question, url: question_path(@question), method: :patch do |f| %>
  <div class="field<%= ' field_error' if @question.errors.any? %>">
    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <%= f.label :title %>
      </div>

      <div class="col-sm-10">
        <%= f.text_field :title, placeholder: 'Title', class: 'form-control' %>
      </div>
    </div>

    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <%= f.label :body %>
      </div>

      <div class="col-sm-10">
        <%= f.text_area :body, class: 'form-control' %>
      </div>
    </div>

    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <%= f.label :description %>
      </div>

      <div class="col-sm-10">
        <%= f.text_area :description %>
      </div>
    </div>
  </div>
  <%= f.submit "Submit question!", class: 'btn btn-primary' %>
<% end %>

app/views/questions/index.html.erb
  <h1 class="text-center">Questions</h1>

  <div><%= link_to "Create new question", new_question_path, class: "btn btn-success ml-3" %></div>

  <div class="container-fluid">
    <% @questions.each do |question| %>
    <article class="card mt-3">
      <div class="card-body">
        <h2> <%= question.title %> </h2>
        <p> <%= question.body %> </p>
        <div> <%= question.description %> </div>
        <time><%= question.time%></time>

        <div class="mt-1">     
          <%= link_to 'Show', question_path(question), class: "btn btn-primary" %>
          <%= link_to 'Edit', edit_question_path(question), class: "btn btn-secondary" %>
          <%= link_to 'Destroy', question_path(question), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: "btn btn-danger"%> 
        </div>     
      </div>
    </article>
    <%end %>
  <div>

app/views/questions/new.html.erb
<turbo-frame id="new_question">
  <h1>New Question</h1>

  <%= render "form" %>
</turbo-frame>

app/views/questions/show.html.erb
<div>
  <h1 class="mb-4"><%= @question.title %></h1>

  <p class="lead my-3">
    <%= @question.body %>
  </p>

  <p class="lead my-3">
    <%= @question.description %>
  </p>

  <time datetime="<%= @question.time %>">
    <%= @question.time %>
  </time>
</div>

app/views/shared/_form_errors.erb
<% if object.errors.any? %>
 <div class="alert alert-danger">
   <ul class="mb-0">
     <% object.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
     <% end %>
   </ul>
 </div>
<% end %>